#!/usr/bin/env python3
"""
Assemble the self-generated enterprise tables + questions into MMQA-format JSON.

Inputs (from input directory):
  * tables/*.csv          (denormalized tables)
  * tables/pk_fk_relations.json  (PK/FK info, generated by generate_tables.py)
  * question_answers.json (QA pairs, generated by generate_question_answer.py)

Outputs (placed in input_dir/assembled_json/ by default, or custom -o dir):
  * self.json               (dirty_MMQA split format)
  * merged_self.json        (dirty_merged_MMQA format)
  * question_type_stats.json (question type statistics)

Usage:
    python assemble_self.py -i /path/to/input_dir [-o /path/to/output_dir]
    If -o is not given, output files are written to input_dir/assembled_json/.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path
from typing import Any

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]

def load_table_specs(table_schema_path: Path) -> list[dict[str, Any]]:
    """Table order and table/column descriptions, read from table_schema.yaml."""
    with table_schema_path.open("r", encoding="utf-8") as f:
        schema = yaml.safe_load(f) or {}
    specs = []
    for table in schema.get("tables", []) or []:
        specs.append({
            "name": table["name"],
            "description": table.get("description", ""),
            "columns": {c["name"]: c.get("description", "") for c in table.get("columns", [])},
        })
    if not specs:
        raise ValueError(f"No tables defined in {table_schema_path}")
    return specs


def infer_value(raw: str) -> Any:
    """Convert a CSV cell into int/float/None/string, preserving text values."""
    value = raw.strip()
    if value == "":
        return None
    try:
        return int(value)
    except ValueError:
        pass
    try:
        return float(value)
    except ValueError:
        pass
    return raw


def load_table(spec: dict[str, Any], tables_dir: Path) -> dict[str, Any]:
    csv_path = tables_dir / f"{spec['name']}.csv"
    with csv_path.open("r", encoding="utf-8-sig", newline="") as fh:
        reader = csv.reader(fh)
        rows = list(reader)
    if not rows:
        raise ValueError(f"Empty CSV: {csv_path}")
    columns = [c.strip() for c in rows[0]]
    content = [[infer_value(cell) for cell in row] for row in rows[1:]]
    return {"table_columns": columns, "table_content": content}


def build_descriptions(table_specs: list[dict[str, Any]]) -> dict[str, Any]:
    table_descs = []
    column_descs = []
    for spec in table_specs:
        table_descs.append({"name": spec["name"], "description": spec["description"]})
        for col_name, col_desc in spec["columns"].items():
            column_descs.append(
                {"table": spec["name"], "name": col_name, "description": col_desc}
            )
    return {"tables": table_descs, "columns": column_descs}


def natural_id_key(qa: dict[str, Any]) -> int:
    """
    Return a numeric sort key based on 'question_id' (preferred) or 'id' (fallback).
    This ensures sorting by numeric ID rather than string (e.g., 2 < 10), and
    handles string ids like "q_0001" by extracting the trailing digits.
    """
    qid = qa.get("question_id")
    if qid is None:
        qid = qa.get("id", 0)
    try:
        return int(qid)
    except (TypeError, ValueError):
        match = re.search(r"(\d+)\s*$", str(qid))
        return int(match.group(1)) if match else 0


def convert_answer(answer: Any) -> Any:
    """Render a question_answers.json answer in dirty_MMQA convention.

    dirty_MMQA stores ``answer`` as a list of rows (``[[...], ...]``) for
    multi-value retrieval, or a plain value otherwise. Flat lists of scalars
    are promoted to single-column rows.
    """
    if isinstance(answer, list):
        if answer and all(isinstance(v, list) for v in answer):
            return answer  # already a list of rows
        return [[v] for v in answer]  # [] stays [], flat scalars become rows
    return answer


def compute_kg_stats(
    kgschema_path: Path | None,
    instances_path: Path | None,
    tables: list[dict[str, Any]],
) -> dict[str, Any]:
    """Compute summary statistics about the knowledge graph schema/instances/tables.

    * num_entity_types / num_relation_types / num_properties come from kgschema.yaml
      (schema-level counts).
    * num_entity_instances / num_relation_instances come from instances.json
      (generated data volume).
    * num_table_rows is the total number of data rows across the assembled tables.
    """
    num_entity_types = 0
    num_relation_types = 0
    num_properties = 0
    if kgschema_path is not None and kgschema_path.is_file():
        with kgschema_path.open("r", encoding="utf-8") as f:
            schema = yaml.safe_load(f) or {}
        entities = schema.get("entities", {}) or {}
        relations = schema.get("relations", []) or []
        num_entity_types = len(entities)
        num_relation_types = len(relations)
        num_properties = sum(len((spec or {}).get("properties", {}) or {}) for spec in entities.values())
        num_properties += sum(len((rel or {}).get("properties", {}) or {}) for rel in relations)

    num_entity_instances = 0
    num_relation_instances = 0
    if instances_path is not None and instances_path.is_file():
        with instances_path.open("r", encoding="utf-8") as f:
            instances = json.load(f)
        num_entity_instances = sum(len(v) for v in (instances.get("entities", {}) or {}).values())
        num_relation_instances = sum(len(v) for v in (instances.get("relations", {}) or {}).values())

    num_table_rows = sum(len(t["table_content"]) for t in tables)

    return {
        "num_entity_types": num_entity_types,
        "num_relation_types": num_relation_types,
        "num_properties": num_properties,
        "num_entity_instances": num_entity_instances,
        "num_relation_instances": num_relation_instances,
        "num_table_rows": num_table_rows,
    }


def format_kg_stats(stats: dict[str, Any], type_stats: dict[str, dict[str, Any]] | None = None) -> str:
    lines = [
        f"Number of entities: {stats['num_entity_types']}",
        f"Number of relation instances: {stats['num_relation_instances']}",
        f"Number of entity instances: {stats['num_entity_instances']}",
        f"Number of properties: {stats['num_properties']}",
        f"Number of table rows (total): {stats['num_table_rows']}",
        "",
        "--- additional detail ---",
        f"Number of relation types: {stats['num_relation_types']}",
    ]
    if type_stats:
        total_questions = sum(t["num"] for t in type_stats.values())
        lines.append("")
        lines.append(f"Number of questions (total): {total_questions}")
        lines.append("Number of questions by type:")
        for qtype in sorted(type_stats):
            lines.append(f"  {qtype}: {type_stats[qtype]['num']}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Assemble MMQA format from self-generated data.")
    parser.add_argument("-i", "--input-dir", required=True,
                        help="Directory containing question_answers.json and tables/ subdirectory.")
    parser.add_argument("-o", "--output-dir", default=None,
                        help="Output base directory (default: input_dir/assembled_json)")
    parser.add_argument("--kgschema", default=None,
                        help="Path to kgschema.yaml (default: input_dir/../meta/kgschema.yaml)")
    parser.add_argument("--table-schema", default=None,
                        help="Path to table_schema.yaml (default: input_dir/../meta/table_schema.yaml)")
    parser.add_argument("--instances", default=None,
                        help="Path to instances.json (default: input_dir/instances.json)")
    parser.add_argument("--stats-file", default=None,
                        help="Path to write the KG statistics text file (default: input_dir/stats.txt)")
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    if not input_dir.is_dir():
        raise NotADirectoryError(f"Input directory not found: {input_dir}")
    table_schema_path = (
        Path(args.table_schema) if args.table_schema
        else input_dir.parent / "meta" / "table_schema.yaml"
    )
    table_specs = load_table_specs(table_schema_path)

    questions_path = input_dir / "question_answers.json"
    tables_dir = input_dir / "tables"
    if not questions_path.is_file():
        raise FileNotFoundError(f"question_answers.json not found in {input_dir}")
    if not tables_dir.is_dir():
        raise NotADirectoryError(f"tables/ subdirectory not found in {input_dir}")

    # Determine output location: default to input_dir/assembled_json
    if args.output_dir is None:
        out_base = input_dir / "assembled_json"
    else:
        out_base = Path(args.output_dir)
    out_base.mkdir(parents=True, exist_ok=True)

    # Load questions
    with questions_path.open("r", encoding="utf-8") as f:
        questions = json.load(f)

    # Sort by numeric question_id (or id fallback)
    questions = sorted(questions, key=natural_id_key)

    # Load PK/FK info from the pk_fk_relations.json file if it exists
    pk_fk_path = tables_dir / "pk_fk_relations.json"
    if pk_fk_path.exists():
        with pk_fk_path.open("r", encoding="utf-8") as f:
            pk_fk_data = json.load(f)
        pk_fk_map = {
            item["table_name"]: {
                "primary_key": item.get("primary_key", []),
                "foreign_keys": item.get("foreign_keys", [])
            }
            for item in pk_fk_data
        }
    else:
        pk_fk_map = {}
        print(f"Warning: {pk_fk_path} not found. No PK/FK information included.")

    # Load tables and attach PK/FK info
    table_names = [spec["name"] for spec in table_specs]
    tables = []
    for spec in table_specs:
        table_content = load_table(spec, tables_dir)
        table_info = {
            "table_columns": table_content["table_columns"],
            "table_content": table_content["table_content"],
            "primary_key": pk_fk_map.get(spec["name"], {}).get("primary_key", []),
            "foreign_keys": pk_fk_map.get(spec["name"], {}).get("foreign_keys", [])
        }
        tables.append(table_info)

    descriptions = build_descriptions(table_specs)

    # --- Question type statistics ---
    type_stats: dict[str, dict[str, Any]] = {}
    for qa in questions:
        qtype = qa.get("type", "unknown")
        if qtype not in type_stats:
            type_stats[qtype] = {"num": 0, "list": []}
        type_stats[qtype]["num"] += 1
        qid = qa.get("question_id")
        if qid is None:
            qid = qa.get("id")
        type_stats[qtype]["list"].append(qid)

    # 1) Split format
    self_items = []
    for idx, qa in enumerate(questions):
        self_items.append(
            {
                "id_": idx,
                "table_names": table_names,
                "tables": tables,
                "descriptions": descriptions,
                "Question": qa["question"],
                "answer": convert_answer(qa["answer"]),
                "type": qa.get("type", "unknown"),
            }
        )

    # 2) Merged format
    merged_item = {
        "id_": 1000000,
        "table_names": table_names,
        "tables": tables,
        "descriptions": descriptions,
        "qa_pairs": [
            {
                "source_item_id": idx,
                "Question": qa["question"],
                "answer": convert_answer(qa["answer"]),
                "type": qa.get("type", "unknown"),
            }
            for idx, qa in enumerate(questions)
        ],
    }

    # Write outputs
    self_path = out_base / "self.json"
    merged_path = out_base / "merged_self.json"
    stats_path = out_base / "question_type_stats.json"

    self_path.write_text(
        json.dumps(self_items, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    merged_path.write_text(
        json.dumps([merged_item], ensure_ascii=False, indent=2), encoding="utf-8"
    )
    stats_path.write_text(
        json.dumps(type_stats, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    print(f"wrote {self_path} ({len(self_items)} items)")
    print(f"wrote {merged_path} (1 item, {len(merged_item['qa_pairs'])} qa_pairs)")
    print(f"wrote {stats_path}")

    # --- KG statistics (entities/relations/properties/table rows) ---
    kgschema_path = Path(args.kgschema) if args.kgschema else input_dir.parent / "meta" / "kgschema.yaml"
    instances_path = Path(args.instances) if args.instances else input_dir / "instances.json"
    kg_stats_path = Path(args.stats_file) if args.stats_file else input_dir / "stats.txt"

    kg_stats = compute_kg_stats(kgschema_path, instances_path, tables)
    kg_stats_path.write_text(format_kg_stats(kg_stats, type_stats), encoding="utf-8")
    if not kgschema_path.is_file():
        print(f"Warning: {kgschema_path} not found. Entity/relation type and property counts left at 0.")
    if not instances_path.is_file():
        print(f"Warning: {instances_path} not found. Entity/relation instance counts left at 0.")
    print(f"wrote {kg_stats_path}")


if __name__ == "__main__":
    main()
